# All SpaceVim option below [option] section
[options]
  enable_googlesuggest = false
  enable_statusline_mode = true
  max_column = 80
  guifont = 'Rec Mono Casual:h12'
  relativenumber = false
  statusline_separator = 'arrow'
  enable_key_frequency = true
  enable_cursorcolumn = false
  enable_tabline_filetype_icon = true
  enable_os_fileformat_icon = true
  github_username = 'SteamedFish'
  enable_vimfiler_gitstatus = true
  enable_vimfile_filetypeicon = true
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  enable_powerline_fonts = true
  lint_on_the_fly = true

[[layers]]
  name = "VersionControl"
[[layers]]
  name = "autocomplete"
[[layers]]
  name = "checkers"
[[layers]]
  name = "colorscheme"
[[layers]]
  name = "cscope"
[[layers]]
  name = "debug"
[[layers]]
  name = "default"
[[layers]]
  name = "edit"
[[layers]]
  name = "floobits"
[[layers]]
  name = "git"
[[layers]]
  name = "github"
#[[layers]]
#  name = "gtags"
[[layers]]
  name = "lang#asciidoc"
[[layers]]
  name = "lang#c"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#extra"
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lang#graphql"
[[layers]]
  name = "lang#html"
[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#latex"
[[layers]]
  name = "lang#lisp"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "lang#perl"
[[layers]]
  name = "lang#php"
[[layers]]
  name = "lang#plantuml"
[[layers]]
  name = "lang#python"
[[layers]]
  name = "lang#puppet"
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "lsp"
#  filetypes = [
#    "python"
#  ]
[[layers]]
  name = "shell"
  default_position = 'bottom'
[[layers]]
  name = "tags"
[[layers]]
  name = "sudo"
[[layers]]
  name = "tests"
[[layers]]
  name = "tumx"
[[layers]]
  name = "tools"
[[layers]]
  name = "tools#dash"
[[layers]]
  name = "ui"
[[layers]]
  name = "denite"

[[custom_plugins]]
    repo = "wakatime/vim-wakatime"
    merged = false
